import Article from './components/article.vue'
import ContentView from './components/content.vue'
export default[
	{
		path:'/js',component:ContentView
	},
	{
		path:'/pl',component:ContentView
	},
	{
		path:'/gj',component:ContentView
	},
		{
		path:'/wh',component:ContentView
	},
		{
		path:'/zs',component:ContentView
	},
		{
		path:'/ft',component:ContentView
	},
		{
		path:'/jk',component:ContentView
	},
		{
		path:'/sh',component:ContentView
	},
		{
		path:'/ly',component:ContentView
	},
		{
		path:'/db',component:ContentView
	},
		{
		path:'/fj',component:ContentView
	},
		{
		path:'/gy',component:ContentView
	},
		{
		path:'/tp',component:ContentView
	},
		{
		path:'/yl',component:ContentView
	},
		{
		path:'/jbf',component:ContentView
	},
		{
		path:'/yw',component:ContentView
	},
		{
		path:'/xg',component:ContentView
	},
		{
		path:'/nd',component:ContentView
	},
	{
		path:'/zx',component:ContentView
	},
    {
		path:'/cj',component:ContentView
	},
	{
		path:'/',redirect:"/yw"
	},
	{
		path:'*',redirect:"/yw"
	},
	{
		path:'/article/:id',component:Article
	}
]